<?php

use function Livewire\Volt\{title};

title('Template - Übersicht');

?>

<x-intranet-app-template::template-layout heading="Template App" subheading="Übersicht">
    {{-- Index content is automatically generated by the layout --}}
</x-intranet-app-template::template-layout>